INSERT INTO UTILISATEUR (EMAIL, PASSWORD, ROLE)
VALUES ('admin@test.com', 'admin123', 'ADMIN');

INSERT INTO UTILISATEUR (EMAIL, PASSWORD, ROLE)
VALUES ('gest@test.com', 'gest123', 'GESTIONNAIRE');

INSERT INTO UTILISATEUR (EMAIL, PASSWORD, ROLE)
VALUES ('agent@test.com', 'agent123', 'AGENT');

INSERT INTO UTILISATEUR (EMAIL, PASSWORD, ROLE)
VALUES ('client@test.com', 'client123', 'CLIENT');

COMMIT;