-- Test 1 : Vérification montant prime minimum
-- Vérifie que TRG_VERIF_MONTANT empêche un montant inférieur au minimum
INSERT INTO SOUSCRIPTION (ID_CLIENT, ID_AGENT, ID_PRODUIT, MONTANT_PRIME, DUREE)
VALUES (1, 1, 1, 50, 12);
-- Attendu : ERREUR "Montant prime inferieur au minimum du produit"

-- Test 2 : Calcul automatique de la date de fin
INSERT INTO SOUSCRIPTION (ID_CLIENT, ID_AGENT, ID_PRODUIT, MONTANT_PRIME, DUREE)
VALUES (1, 1, 1, 200, 12);
SELECT DATE_SOUSCRIPTION, DATE_FIN FROM SOUSCRIPTION WHERE ID_SOUSCRIPTION = 1;

-- Test 3 : Calcul automatique des commissions
SELECT * FROM COMMISSION WHERE ID_SOUSCRIPTION = 1;
-- Attendu : Commission = MONTANT_PRIME * TAUX_COMMISSION / 100

-- Test 4 : Vérification montant paiement
INSERT INTO PAIEMENT (ID_SOUSCRIPTION, MONTANT, MODE_PAIEMENT, STATUT)
VALUES (1, 0, 'CB', 'VALIDE');
-- Attendu : ERREUR "Montant paiement invalide"

-- Test 5 : Audit des clients
-- Insert
INSERT INTO CLIENT (NUMERO_IDENTITE, NOM, PRENOM, TELEPHONE, PROFESSION)
VALUES ('ID123456', 'SORE', 'Linda', '7743878600', 'Comptable');
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='CLIENT';

-- Update
UPDATE CLIENT SET NOM='Durand' WHERE ID_CLIENT=1;
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='CLIENT' AND OPERATION='UPDATE';

-- Delete
DELETE FROM CLIENT WHERE ID_CLIENT=1;
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='CLIENT' AND OPERATION='DELETE';

-- Test 6 : Audit des agents
INSERT INTO AGENT_COMMERCIAL (NUMERO_MATRICULE, NOM, PRENOM, TELEPHONE)
VALUES ('AG1001', 'OUEDRAOGO', 'Paul', '0722222222');
UPDATE AGENT_COMMERCIAL SET NOM='Legrand' WHERE ID_AGENT=1;
DELETE FROM AGENT_COMMERCIAL WHERE ID_AGENT=1;
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='AGENT_COMMERCIAL';

-- Test 7 : Audit des souscriptions
INSERT INTO SOUSCRIPTION (ID_CLIENT, ID_AGENT, ID_PRODUIT, MONTANT_PRIME, DUREE)
VALUES (2, 2, 2, 200, 12);
UPDATE SOUSCRIPTION SET MONTANT_PRIME=250 WHERE ID_SOUSCRIPTION=2;
DELETE FROM SOUSCRIPTION WHERE ID_SOUSCRIPTION=2;
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='SOUSCRIPTION';

-- Test 8 : Audit des produits
INSERT INTO PRODUIT (NOM_PRODUIT, TYPE_PRODUIT, MONTANT_MIN, TAUX_COMMISSION)
VALUES ('Assurance Vie Classique', 'Vie', 100, 10);
UPDATE PRODUIT SET TAUX_COMMISSION=12 WHERE ID_PRODUIT=1;
DELETE FROM PRODUIT WHERE ID_PRODUIT=1;
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='PRODUIT';

-- Test 9 : Vues principales
SELECT * FROM V_CLIENT;
SELECT * FROM V_AGENT;
SELECT * FROM V_PRODUIT;
SELECT * FROM V_COMMISSION;
SELECT * FROM V_PERFORMANCE_AGENT;
SELECT * FROM V_SOUSCRIPTION_DETAIL;
SELECT * FROM V_PAIEMENT_DETAIL;

-- Test 10 : Contraintes d'intégrité
-- Client inexistant
INSERT INTO SOUSCRIPTION (ID_CLIENT, ID_AGENT, ID_PRODUIT, MONTANT_PRIME, DUREE)
VALUES (999, 1, 1, 200, 12); 


-- Test 11 : Transaction compliquée
BEGIN
  INSERT INTO CLIENT (NUMERO_IDENTITE, NOM, PRENOM, TELEPHONE, PROFESSION)
  VALUES ('ID987654', 'Martin', 'Claire', '0711111111', 'Infirmière');
  
  INSERT INTO AGENT_COMMERCIAL (NUMERO_MATRICULE, NOM, PRENOM, TELEPHONE)
  VALUES ('AG1002', 'Bernard', 'Luc', '0733333333');

  INSERT INTO PRODUIT (NOM_PRODUIT, TYPE_PRODUIT, MONTANT_MIN, TAUX_COMMISSION)
  VALUES ('Assurance Vie Premium', 'Vie', 150, 15);

  INSERT INTO SOUSCRIPTION (ID_CLIENT, ID_AGENT, ID_PRODUIT, MONTANT_PRIME, DUREE)
  VALUES (3, 3, 3, 200, 12);
  
  INSERT INTO PAIEMENT (ID_SOUSCRIPTION, MONTANT, MODE_PAIEMENT, STATUT)
  VALUES (3, 200, 'Virement', 'VALIDE');
END;
-- Vérifier : Date fin, commission, audit log et paiements correctement générés
SELECT * FROM SOUSCRIPTION WHERE ID_SOUSCRIPTION=3;
SELECT * FROM COMMISSION WHERE ID_SOUSCRIPTION=3;
SELECT * FROM AUDIT_LOG WHERE NOM_TABLE='SOUSCRIPTION' AND ID_ENREGISTREMENT=3;
SELECT * FROM V_PAIEMENT_DETAIL WHERE CODE_SOUSCRIPTION='SO-00003';