-- Table UTILISATEUR
CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    STATUT VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUT IN ('ACTIVE','DESACTIVE','BLOQUEE')),
    ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('CLIENT','AGENT','GESTIONNAIRE','ADMIN')),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
);

-- Table CLIENT
CREATE TABLE CLIENT (
    ID_CLIENT NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_IDENTITE VARCHAR2(20) NOT NULL UNIQUE,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    DATE_NAISSANCE DATE,
    TELEPHONE VARCHAR2(20) NOT NULL,
    ADRESSE VARCHAR2(255),
    PROFESSION VARCHAR2(100) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE DEFAULT NULL
);

-- Table AGENT_COMMERCIAL
CREATE TABLE AGENT_COMMERCIAL (
    ID_AGENT NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_MATRICULE VARCHAR2(20) NOT NULL UNIQUE,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    TELEPHONE VARCHAR2(20) NOT NULL,
    DATE_EMBAUCHE DATE DEFAULT SYSDATE NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE DEFAULT NULL
);

-- Table PRODUIT
CREATE TABLE PRODUIT (
    ID_PRODUIT NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM_PRODUIT VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    TYPE_PRODUIT VARCHAR2(50) NOT NULL,
    MONTANT_MIN NUMBER(15,2) NOT NULL CHECK (MONTANT_MIN >= 0),
    TAUX_COMMISSION NUMBER(5,2) NOT NULL CHECK (TAUX_COMMISSION >= 0),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    DELETED_AT DATE DEFAULT NULL
);

-- Table SOUSCRIPTION 
CREATE TABLE SOUSCRIPTION (
    ID_SOUSCRIPTION NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATE_SOUSCRIPTION DATE DEFAULT SYSDATE NOT NULL,
    DUREE NUMBER NOT NULL CHECK (DUREE > 0),
    DATE_FIN DATE NOT NULL,
    MONTANT_PRIME NUMBER(15,2) NOT NULL CHECK (MONTANT_PRIME > 0),
    STATUT VARCHAR2(20) NOT NULL CHECK (STATUT IN ('ACTIVE', 'RESILIEE', 'TERMINEE')),
    ID_CLIENT NUMBER(38,0) NOT NULL,
    ID_AGENT NUMBER(38,0) NOT NULL,
    ID_PRODUIT NUMBER(38,0) NOT NULL,
    DELETED_AT DATE DEFAULT NULL,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    FOREIGN KEY (ID_AGENT) REFERENCES AGENT_COMMERCIAL(ID_AGENT),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
);
-- Table PAIEMENT
CREATE TABLE PAIEMENT (
    ID_PAIEMENT NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATE_PAIEMENT DATE DEFAULT SYSDATE NOT NULL,
    MONTANT NUMBER(15,2) NOT NULL CHECK (MONTANT > 0),
    MODE_PAIEMENT VARCHAR2(50) NOT NULL,
    STATUT VARCHAR2(20) NOT NULL CHECK (STATUT IN ('VALIDE', 'EN_ATTENTE', 'ECHEC')),
    DEVISE VARCHAR2(10) DEFAULT 'USD' NOT NULL,
    ID_SOUSCRIPTION NUMBER(38,0) NOT NULL,
    FOREIGN KEY (ID_SOUSCRIPTION) REFERENCES SOUSCRIPTION(ID_SOUSCRIPTION)
);
-- Table CAMPAGNE_COMMISSION
CREATE TABLE CAMPAGNE_COMMISSION (
    ID_CAMPAGNE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATE_DEBUT  DATE NOT NULL,
    DATE_FIN    DATE NOT NULL,
    DATE_CALCUL DATE NOT NULL,
    ID_AGENT    NUMBER NULL
);

-- Table COMMISSION
CREATE TABLE COMMISSION (
    ID_COMMISSION NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MONTANT NUMBER(15,2) NOT NULL CHECK (MONTANT >= 0),
    DATE_CALCUL DATE DEFAULT SYSDATE NOT NULL,
    ID_AGENT NUMBER(38,0) NOT NULL,
    ID_SOUSCRIPTION NUMBER(38,0) NOT NULL,
    ID_CAMPAGNE NUMBER NOT NULL,

    -- Contraintes FK
    FOREIGN KEY (ID_AGENT) REFERENCES AGENT_COMMERCIAL(ID_AGENT),
    FOREIGN KEY (ID_SOUSCRIPTION) REFERENCES SOUSCRIPTION(ID_SOUSCRIPTION),
    FOREIGN KEY (ID_CAMPAGNE) REFERENCES CAMPAGNE_COMMISSION(ID_CAMPAGNE)
);

-- Table AUDIT_LOG
CREATE TABLE AUDIT_LOG (
    ID_AUDIT NUMBER(38,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM_TABLE VARCHAR2(50) NOT NULL,
    OPERATION VARCHAR2(10) NOT NULL,
    ID_ENREGISTREMENT NUMBER(38,0) NOT NULL,
    NOM_COLONNE VARCHAR2(50),
    ANCIENNE_VALEUR VARCHAR2(4000),
    NOUVELLE_VALEUR VARCHAR2(4000),
    UTILISATEUR VARCHAR2(50) DEFAULT USER,
    DATE_MODIFICATION TIMESTAMP DEFAULT SYSTIMESTAMP
);

