-- Index pour optimiser les requêtes
CREATE INDEX IDX_SOUSCRIPTION_AGENT ON SOUSCRIPTION(ID_AGENT);
CREATE INDEX IDX_SOUSCRIPTION_CLIENT ON SOUSCRIPTION(ID_CLIENT);
CREATE INDEX IDX_AUDIT_LOG_RECORD ON AUDIT_LOG(NOM_TABLE, ID_ENREGISTREMENT);
