SET SERVEROUTPUT ON;

-- BEGIN
--     -- Supprimer les tables dans l'ordre des dépendances
--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE COMMISSION CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE PAIEMENT CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE SOUSCRIPTION CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE CAMPAGNE_COMMISSION CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE PRODUIT CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE AGENT_COMMERCIAL CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE CLIENT CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     BEGIN
--         EXECUTE IMMEDIATE 'DROP TABLE UTILISATEUR CASCADE CONSTRAINTS';
--     EXCEPTION WHEN OTHERS THEN NULL; END;

--     COMMIT;

--     DBMS_OUTPUT.PUT_LINE('Toutes les tables ont été supprimées avec succès.');
-- END;
-- /


-- SELECT ROLE, PASSWORD_REQUIRED
-- FROM DBA_ROLES


SELECT GRANTEE AS ROLE,
       PRIVILEGE,
       ADMIN_OPTION
FROM DBA_SYS_PRIVS
ORDER BY GRANTEE, PRIVILEGE;