CREATE USER GESTION IDENTIFIED BY Password06# 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS;

-- Donne les privilèges de base pour créer des objets
GRANT CREATE SESSION, CREATE PROCEDURE, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO GESTION;

-- Si tu veux pouvoir créer des triggers ou packages
GRANT CREATE TRIGGER, CREATE TYPE TO GESTION;