-- -- =========================================================
-- -- Création propre de l'utilisateur ASSURANCEVIE
-- -- =========================================================

-- -- 1) Création de l'utilisateur
-- CREATE USER ASSURANCEVIE
-- IDENTIFIED BY "Assurancevie123#"
-- DEFAULT TABLESPACE USERS
-- TEMPORARY TABLESPACE TEMP
-- QUOTA UNLIMITED ON USERS;

-- -- 2) Privilèges minimum nécessaires
-- GRANT CREATE SESSION TO ASSURANCEVIE;
-- GRANT CREATE TABLE TO ASSURANCEVIE;
-- GRANT CREATE VIEW TO ASSURANCEVIE;
-- GRANT CREATE PROCEDURE TO ASSURANCEVIE;
-- GRANT CREATE TRIGGER TO ASSURANCEVIE;
-- GRANT CREATE SEQUENCE TO ASSURANCEVIE;
-- GRANT CREATE INDEX TO ASSURANCEVIE;

-- -- 3) (Optionnel) Pour éviter tout blocage futur sur les contraintes
-- GRANT ALTER SESSION TO ASSURANCEVIE;

-- -- =========================================================
-- -- Fin
-- -- =========================================================
-- =========================================================
-- Correction des privilèges du user EXISTANT ASSURANCEVIE
-- =========================================================

GRANT CREATE SESSION TO ASSURANCEVIE;

GRANT CREATE TABLE TO ASSURANCEVIE;
GRANT CREATE VIEW TO ASSURANCEVIE;
GRANT CREATE PROCEDURE TO ASSURANCEVIE;
GRANT CREATE TRIGGER TO ASSURANCEVIE;
GRANT CREATE SEQUENCE TO ASSURANCEVIE;

GRANT ALTER SESSION TO ASSURANCEVIE;

-- quota pour créer des objets
ALTER USER ASSURANCEVIE QUOTA UNLIMITED ON USERS;

SELECT username, account_status
FROM dba_users
WHERE username = 'ASSURANCEVIE';

-- Connexion en tant que SYSTEM ou un DBA
ALTER USER ASSURANCEVIE QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO ASSURANCEVIE;
GRANT CREATE TABLE TO ASSURANCEVIE;
GRANT CREATE VIEW TO ASSURANCEVIE;
GRANT CREATE PROCEDURE TO ASSURANCEVIE;
GRANT CREATE TRIGGER TO ASSURANCEVIE;
GRANT CREATE SEQUENCE TO ASSURANCEVIE;
GRANT ALTER SESSION TO ASSURANCEVIE;