CREATE OR REPLACE VIEW V_HISTO_CLIENT AS
SELECT 
    s.ID_CLIENT,
    c.NOM || ' ' || c.PRENOM AS CLIENT,
    c.TELEPHONE,
    s.ID_SOUSCRIPTION,
    p.NOM_PRODUIT,
    a.NOM || ' ' || a.PRENOM AS AGENT,
    s.STATUT,
    s.MONTANT_PRIME
FROM SOUSCRIPTION s
JOIN CLIENT c ON s.ID_CLIENT = c.ID_CLIENT
JOIN PRODUIT p ON s.ID_PRODUIT = p.ID_PRODUIT
JOIN AGENT_COMMERCIAL a ON s.ID_AGENT = a.ID_AGENT;