-- Vue Souscription Detail
CREATE OR REPLACE VIEW V_SOUSCRIPTION_DETAIL AS
SELECT 
    'SO-' || LPAD(s.ID_SOUSCRIPTION, 5, '0') AS CODE_SOUSCRIPTION,
    vc.CODE_CLIENT,
    vc.NOM AS NOM_CLIENT,
    vc.PRENOM AS PRENOM_CLIENT,
    vc.TELEPHONE,
    va.CODE_AGENT,
    va.NOM AS NOM_AGENT,
    va.PRENOM AS PRENOM_AGENT,
    vp.CODE_PRODUIT,
    vp.NOM_PRODUIT,
    vp.TYPE_PRODUIT,
    s.DATE_SOUSCRIPTION,
    s.DATE_FIN,
    s.MONTANT_PRIME,
    s.STATUT
FROM SOUSCRIPTION s
JOIN V_CLIENT vc ON vc.ID_CLIENT = s.ID_CLIENT
JOIN V_AGENT va ON va.ID_AGENT = s.ID_AGENT
JOIN V_PRODUIT vp ON vp.ID_PRODUIT = s.ID_PRODUIT;