-- Droits ROLE_AGENT
GRANT SELECT ON V_CLIENT TO ROLE_AGENT;
GRANT SELECT ON V_AGENT TO ROLE_AGENT;
GRANT SELECT ON V_PRODUIT TO ROLE_AGENT;
GRANT SELECT ON V_SOUSCRIPTION_DETAIL TO ROLE_AGENT;
GRANT SELECT ON V_PAIEMENT_DETAIL TO ROLE_AGENT;

-- ROLE_GESTIONNAIRE : analyse via les vues
GRANT SELECT ON V_PERFORMANCE_AGENT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_STAT_PRODUIT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_COMMISSION TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_SOUSCRIPTION_DETAIL TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_PRODUIT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_CLIENT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_AGENT TO ROLE_GESTIONNAIRE;

-- ROLE_ADMIN : gestion complète des tables
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENT TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON AGENT_COMMERCIAL TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUIT TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON SOUSCRIPTION TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAIEMENT TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON COMMISSION TO ROLE_ADMIN;
GRANT SELECT ON AUDIT_LOG TO ROLE_ADMIN;

-- Attribution des rôles 
GRANT ROLE_AGENT TO user_agent;
GRANT ROLE_GESTIONNAIRE TO user_gestionnaire;
GRANT ROLE_ADMIN TO user_admin;