
-- Droits ROLE_CLIENT
GRANT EXECUTE ON Ajouter_Client TO ROLE_CLIENT;
GRANT EXECUTE ON Modifier_Client TO ROLE_CLIENT;
GRANT EXECUTE ON Historique_Client TO ROLE_CLIENT;
GRANT EXECUTE ON Ajouter_Souscription TO ROLE_CLIENT;
GRANT EXECUTE ON Ajouter_Paiement TO ROLE_CLIENT;
-- Droits ROLE_AGENT
GRANT EXECUTE ON Etat_Portefeuille_Agent TO ROLE_AGENT;
GRANT EXECUTE ON Ajouter_Client TO ROLE_AGENT;
GRANT EXECUTE ON Modifier_Client TO ROLE_AGENT;
GRANT EXECUTE ON Historique_Client TO ROLE_AGENT;
GRANT EXECUTE ON Ajouter_Souscription TO ROLE_AGENT;
GRANT EXECUTE ON Ajouter_Paiement TO ROLE_AGENT;


-- Droits ROLE_GESTIONNAIRE
GRANT EXECUTE ON Ajouter_Client TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Modifier_Client TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Generer_Rapport_Performance_Agents TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Historique_Client TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Ajouter_Produit TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Modifier_Produit TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Supprimer_Produit TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Ajouter_Agent TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Modifier_Agent TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Supprimer_Agent TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Modifier_Statut_Souscription TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Rechercher_Souscription TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Souscriptions_Proches_Echeance TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Supprimer_Client TO ROLE_GESTIONNAIRE;
GRANT EXECUTE ON Modifier_Statut_Paiement TO ROLE_GESTIONNAIRE;

GRANT EXECUTE ON Global_Execute_Proc_Oracle TO PUBLIC;
COMMIT;