CREATE OR REPLACE FUNCTION USER_ROLE_EXISTS(p_role VARCHAR2) RETURN BOOLEAN IS
BEGIN
    FOR r IN (SELECT 1 FROM SESSION_ROLES WHERE ROLE = UPPER(p_role)) LOOP
        RETURN TRUE;
    END LOOP;
    RETURN FALSE;
END;
/