-- Profile pour les Agents commerciaux
CREATE PROFILE PROFIL_AGENT LIMIT
    SESSIONS_PER_USER 1
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_MAX 5
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;

-- Profile pour les Clients 
CREATE PROFILE PROFIL_CLIENT LIMIT
    SESSIONS_PER_USER 1
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 90
    PASSWORD_REUSE_MAX 5
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;

-- Profile pour les Gestionnaires
CREATE PROFILE PROFIL_GESTIONNAIRE LIMIT
    SESSIONS_PER_USER 2
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 60
    PASSWORD_REUSE_MAX 5
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;

-- Profile pour les Administrateurs
CREATE PROFILE PROFIL_ADMIN LIMIT
    SESSIONS_PER_USER 2
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30
    PASSWORD_REUSE_MAX 3
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;

-- Profile pour le compte applicatif Front-end (APP_CLIENT)
CREATE PROFILE PROFIL_APP LIMIT
    SESSIONS_PER_USER 1
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_REUSE_MAX UNLIMITED
    PASSWORD_VERIFY_FUNCTION ora12c_verify_function;

COMMIT;