-- Vue Commission
CREATE OR REPLACE VIEW V_COMMISSION AS
SELECT 
    va.CODE_AGENT,
    va.NOM AS NOM_AGENT,
    va.PRENOM AS PRENOM_AGENT,
    COUNT(c.ID_COMMISSION) AS NB_COMMISSIONS,
    NVL(SUM(c.MONTANT), 0) AS TOTAL_COMMISSION
FROM COMMISSION c
JOIN V_AGENT va ON va.ID_AGENT = c.ID_AGENT
GROUP BY va.CODE_AGENT, va.NOM, va.PRENOM;
