-- Vue Performance Agent
CREATE OR REPLACE VIEW V_PERFORMANCE_AGENT AS
SELECT 
    va.CODE_AGENT,
    va.NOM,
    va.PRENOM,
    COUNT(s.ID_SOUSCRIPTION) AS NB_VENTES,
    NVL(SUM(s.MONTANT_PRIME), 0) AS CHIFFRE_AFFAIRE
FROM V_AGENT va
LEFT JOIN SOUSCRIPTION s ON va.ID_AGENT = s.ID_AGENT
GROUP BY va.CODE_AGENT, va.NOM, va.PRENOM;