-- Vue Statistique Produit
CREATE OR REPLACE VIEW V_STAT_PRODUIT AS
SELECT 
    vp.CODE_PRODUIT,
    vp.NOM_PRODUIT,
    vp.TYPE_PRODUIT,
    COUNT(s.ID_SOUSCRIPTION) AS NB_VENTES,
    NVL(SUM(s.MONTANT_PRIME), 0) AS TOTAL_VENTE
FROM V_PRODUIT vp
LEFT JOIN SOUSCRIPTION s ON vp.ID_PRODUIT = s.ID_PRODUIT
GROUP BY vp.CODE_PRODUIT, vp.NOM_PRODUIT, vp.TYPE_PRODUIT;


CREATE OR REPLACE VIEW V_PAIEMENT_DETAIL AS
SELECT 
    'PA-' || LPAD(p.ID_PAIEMENT, 5, '0') AS CODE_PAIEMENT,
    'SO-' || LPAD(s.ID_SOUSCRIPTION, 5, '0') AS CODE_SOUSCRIPTION,
    vc.NOM AS NOM_CLIENT,
    vc.PRENOM AS PRENOM_CLIENT,
    p.DATE_PAIEMENT,
    p.MONTANT,
    p.MODE_PAIEMENT,
    p.STATUT
FROM PAIEMENT p
JOIN SOUSCRIPTION s ON s.ID_SOUSCRIPTION = p.ID_SOUSCRIPTION
JOIN V_CLIENT vc ON vc.ID_CLIENT = s.ID_CLIENT;