-- Vue CLIENT
CREATE OR REPLACE VIEW V_CLIENT AS
SELECT 
    ID_CLIENT,
    'CL-' || LPAD(ID_CLIENT, 5, '0') AS CODE_CLIENT,
    NOM,
    PRENOM,
    TELEPHONE,
    PROFESSION
FROM CLIENT;

-- Vue AGENT
CREATE OR REPLACE VIEW V_AGENT AS
SELECT 
    ID_AGENT,
    'AG-' || LPAD(ID_AGENT, 5, '0') AS CODE_AGENT,
    NOM,
    PRENOM,
    TELEPHONE,
    DATE_EMBAUCHE
FROM AGENT_COMMERCIAL;

-- Vue PRODUIT
CREATE OR REPLACE VIEW V_PRODUIT AS
SELECT 
    ID_PRODUIT,
    'PR-' || LPAD(ID_PRODUIT, 5, '0') AS CODE_PRODUIT,
    NOM_PRODUIT,
    TYPE_PRODUIT,
    MONTANT_MIN,
    TAUX_COMMISSION
FROM PRODUIT;

