-- Création des rôles
CREATE ROLE ROLE_AGENT;
CREATE ROLE ROLE_GESTIONNAIRE;
CREATE ROLE ROLE_ADMIN;

-- Droits ROLE_AGENT
GRANT SELECT ON V_CLIENT TO ROLE_AGENT;
GRANT SELECT ON V_AGENT TO ROLE_AGENT;
GRANT SELECT ON V_PRODUIT TO ROLE_AGENT;
GRANT SELECT ON V_SOUSCRIPTION_DETAIL TO ROLE_AGENT;
GRANT SELECT ON V_PAIEMENT_DETAIL TO ROLE_AGENT;
GRANT INSERT ON SOUSCRIPTION TO ROLE_AGENT;
GRANT INSERT ON PAIEMENT TO ROLE_AGENT;

-- Droits ROLE_GESTIONNAIRE
GRANT SELECT ON V_PERFORMANCE_AGENT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_STAT_PRODUIT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_COMMISSION TO ROLE_GESTIONNAIRE;
GRANT SELECT ON V_SOUSCRIPTION_DETAIL TO ROLE_GESTIONNAIRE;
GRANT SELECT, INSERT, UPDATE ON PRODUIT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON CLIENT TO ROLE_GESTIONNAIRE;
GRANT SELECT ON AGENT_COMMERCIAL TO ROLE_GESTIONNAIRE;

-- Droits ROLE_ADMIN
GRANT DBA TO ROLE_ADMIN;

-- Révocation accès direct aux tables pour les agents
REVOKE SELECT ON CLIENT FROM ROLE_AGENT;
REVOKE SELECT ON AGENT_COMMERCIAL FROM ROLE_AGENT;