-- Trigger audit Client
CREATE OR REPLACE TRIGGER TRG_AUDIT_CLIENT
AFTER INSERT OR UPDATE OR DELETE ON CLIENT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOUVELLE_VALEUR)
        VALUES ('CLIENT','INSERT', :NEW.ID_CLIENT,
                'Nom='||:NEW.NOM||', Prénom='||:NEW.PRENOM||', Téléphone='||:NEW.TELEPHONE||', Adresse='||NVL(:NEW.ADRESSE,'')||', Profession='||:NEW.PROFESSION);
    ELSIF DELETING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, ANCIENNE_VALEUR)
        VALUES ('CLIENT','DELETE', :OLD.ID_CLIENT,
                'Nom='||:OLD.NOM||', Prénom='||:OLD.PRENOM||', Téléphone='||:OLD.TELEPHONE||', Adresse='||NVL(:OLD.ADRESSE,'')||', Profession='||:OLD.PROFESSION);
    ELSIF UPDATING THEN
        IF :OLD.NOM != :NEW.NOM OR :OLD.PRENOM != :NEW.PRENOM OR :OLD.TELEPHONE != :NEW.TELEPHONE OR NVL(:OLD.ADRESSE,'') != NVL(:NEW.ADRESSE,'') OR :OLD.PROFESSION != :NEW.PROFESSION THEN
            INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR)
            VALUES ('CLIENT','UPDATE', :NEW.ID_CLIENT,'NOM/PRÉNOM/TÉLÉPHONE/ADRESSE/PROFESSION',
                    'Nom='||:OLD.NOM||', Prénom='||:OLD.PRENOM||', Téléphone='||:OLD.TELEPHONE||', Adresse='||NVL(:OLD.ADRESSE,'')||', Profession='||:OLD.PROFESSION,
                    'Nom='||:NEW.NOM||', Prénom='||:NEW.PRENOM||', Téléphone='||:NEW.TELEPHONE||', Adresse='||NVL(:NEW.ADRESSE,'')||', Profession='||:NEW.PROFESSION);
        END IF;
    END IF;
END;
/

-- Trigger audit Agent Commercial
CREATE OR REPLACE TRIGGER TRG_AUDIT_AGENT
AFTER INSERT OR UPDATE OR DELETE ON AGENT_COMMERCIAL
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOUVELLE_VALEUR)
        VALUES ('AGENT_COMMERCIAL','INSERT', :NEW.ID_AGENT,
                'Nom='||:NEW.NOM||', Prénom='||:NEW.PRENOM||', Téléphone='||:NEW.TELEPHONE||', DateEmbauche='||TO_CHAR(:NEW.DATE_EMBAUCHE,'YYYY-MM-DD'));
    ELSIF DELETING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, ANCIENNE_VALEUR)
        VALUES ('AGENT_COMMERCIAL','DELETE', :OLD.ID_AGENT,
                'Nom='||:OLD.NOM||', Prénom='||:OLD.PRENOM||', Téléphone='||:OLD.TELEPHONE||', DateEmbauche='||TO_CHAR(:OLD.DATE_EMBAUCHE,'YYYY-MM-DD'));
    ELSIF UPDATING THEN
        IF :OLD.NOM != :NEW.NOM OR :OLD.PRENOM != :NEW.PRENOM OR :OLD.TELEPHONE != :NEW.TELEPHONE OR :OLD.DATE_EMBAUCHE != :NEW.DATE_EMBAUCHE THEN
            INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR)
            VALUES ('AGENT_COMMERCIAL','UPDATE', :NEW.ID_AGENT,'NOM/PRÉNOM/TÉLÉPHONE/DATE_EMBAUCHE',
                    'Nom='||:OLD.NOM||', Prénom='||:OLD.PRENOM||', Téléphone='||:OLD.TELEPHONE||', DateEmbauche='||TO_CHAR(:OLD.DATE_EMBAUCHE,'YYYY-MM-DD'),
                    'Nom='||:NEW.NOM||', Prénom='||:NEW.PRENOM||', Téléphone='||:NEW.TELEPHONE||', DateEmbauche='||TO_CHAR(:NEW.DATE_EMBAUCHE,'YYYY-MM-DD'));
        END IF;
    END IF;
END;
/

-- Trigger audit Souscription
CREATE OR REPLACE TRIGGER TRG_AUDIT_SOUSCRIPTION
AFTER INSERT OR UPDATE OR DELETE ON SOUSCRIPTION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOUVELLE_VALEUR)
        VALUES ('SOUSCRIPTION','INSERT', :NEW.ID_SOUSCRIPTION,
                'MontantPrime='||:NEW.MONTANT_PRIME||', Statut='||:NEW.STATUT||', DateFin='||TO_CHAR(:NEW.DATE_FIN,'YYYY-MM-DD'));
    ELSIF DELETING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, ANCIENNE_VALEUR)
        VALUES ('SOUSCRIPTION','DELETE', :OLD.ID_SOUSCRIPTION,
                'MontantPrime='||:OLD.MONTANT_PRIME||', Statut='||:OLD.STATUT||', DateFin='||TO_CHAR(:OLD.DATE_FIN,'YYYY-MM-DD'));
    ELSIF UPDATING THEN
        IF :OLD.MONTANT_PRIME != :NEW.MONTANT_PRIME OR :OLD.STATUT != :NEW.STATUT OR :OLD.DATE_FIN != :NEW.DATE_FIN THEN
            INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR)
            VALUES ('SOUSCRIPTION','UPDATE', :NEW.ID_SOUSCRIPTION,'MONTANTPRIME/STATUT/DATEFIN',
                    'MontantPrime='||:OLD.MONTANT_PRIME||', Statut='||:OLD.STATUT||', DateFin='||TO_CHAR(:OLD.DATE_FIN,'YYYY-MM-DD'),
                    'MontantPrime='||:NEW.MONTANT_PRIME||', Statut='||:NEW.STATUT||', DateFin='||TO_CHAR(:NEW.DATE_FIN,'YYYY-MM-DD'));
        END IF;
    END IF;
END;
/

-- Trigger audit Produit
CREATE OR REPLACE TRIGGER TRG_AUDIT_PRODUIT
AFTER INSERT OR UPDATE OR DELETE ON PRODUIT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOUVELLE_VALEUR)
        VALUES ('PRODUIT','INSERT', :NEW.ID_PRODUIT,
                'NomProduit='||:NEW.NOM_PRODUIT||', Description='||NVL(:NEW.DESCRIPTION,'')||', TypeProduit='||:NEW.TYPE_PRODUIT||', MontantMin='||:NEW.MONTANT_MIN||', TauxCommission='||:NEW.TAUX_COMMISSION);
    ELSIF DELETING THEN
        INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, ANCIENNE_VALEUR)
        VALUES ('PRODUIT','DELETE', :OLD.ID_PRODUIT,
                'NomProduit='||:OLD.NOM_PRODUIT||', Description='||NVL(:OLD.DESCRIPTION,'')||', TypeProduit='||:OLD.TYPE_PRODUIT||', MontantMin='||:OLD.MONTANT_MIN||', TauxCommission='||:OLD.TAUX_COMMISSION);
    ELSIF UPDATING THEN
        IF :OLD.NOM_PRODUIT != :NEW.NOM_PRODUIT OR NVL(:OLD.DESCRIPTION,'') != NVL(:NEW.DESCRIPTION,'') OR :OLD.TYPE_PRODUIT != :NEW.TYPE_PRODUIT OR :OLD.MONTANT_MIN != :NEW.MONTANT_MIN OR :OLD.TAUX_COMMISSION != :NEW.TAUX_COMMISSION THEN
            INSERT INTO AUDIT_LOG(NOM_TABLE, OPERATION, ID_ENREGISTREMENT, NOM_COLONNE, ANCIENNE_VALEUR, NOUVELLE_VALEUR)
            VALUES ('PRODUIT','UPDATE', :NEW.ID_PRODUIT,'NOM/ DESCRIPTION/ TYPE/ MONTANTMIN/ TAUXCOMMISSION',
                    'NomProduit='||:OLD.NOM_PRODUIT||', Description='||NVL(:OLD.DESCRIPTION,'')||', TypeProduit='||:OLD.TYPE_PRODUIT||', MontantMin='||:OLD.MONTANT_MIN||', TauxCommission='||:OLD.TAUX_COMMISSION,
                    'NomProduit='||:NEW.NOM_PRODUIT||', Description='||NVL(:NEW.DESCRIPTION,'')||', TypeProduit='||:NEW.TYPE_PRODUIT||', MontantMin='||:NEW.MONTANT_MIN||', TauxCommission='||:NEW.TAUX_COMMISSION);
        END IF;
    END IF;
END;
/