-- Trigger de calcul de date de fin
CREATE OR REPLACE TRIGGER TRG_DATE_FIN
BEFORE INSERT OR UPDATE ON SOUSCRIPTION
FOR EACH ROW
BEGIN
    :NEW.DATE_FIN := ADD_MONTHS(:NEW.DATE_SOUSCRIPTION, :NEW.DUREE);
END;
/