-- Trigger de vérification du montant
CREATE OR REPLACE TRIGGER TRG_VERIF_MONTANT
BEFORE INSERT OR UPDATE ON SOUSCRIPTION
FOR EACH ROW
DECLARE
    V_MIN NUMBER;
BEGIN
    SELECT MONTANT_MIN INTO V_MIN
    FROM PRODUIT
    WHERE ID_PRODUIT = :NEW.ID_PRODUIT;

    IF :NEW.MONTANT_PRIME < V_MIN THEN
        RAISE_APPLICATION_ERROR(-20001, 'Montant prime inferieur au minimum du produit');
    END IF;
END;
/
