-- Trigger de calcul de commission
CREATE OR REPLACE TRIGGER TRG_CALCUL_COMMISSION
AFTER INSERT ON SOUSCRIPTION
FOR EACH ROW
DECLARE
    V_TAUX NUMBER;
BEGIN
    SELECT TAUX_COMMISSION INTO V_TAUX
    FROM PRODUIT
    WHERE ID_PRODUIT = :NEW.ID_PRODUIT;

    INSERT INTO COMMISSION (MONTANT, ID_AGENT, ID_SOUSCRIPTION)
    VALUES (:NEW.MONTANT_PRIME * V_TAUX / 100, :NEW.ID_AGENT, :NEW.ID_SOUSCRIPTION);
END;
/

